# This YAML file defines the relationship and deployment ordering of your environments.

# The name of the pipeline
name: pipeline-reverse-simorgh1-aws-copilot-cd

# The version of the schema used in this template
version: 1

# This section defines the source artifacts.
source:
  # The name of the provider that is used to store the source artifacts.
  provider: GitHub
  # Additional properties that further specifies the exact location
  # the artifacts should be sourced from. For example, the GitHub provider
  # has the following properties: repository, branch.
  properties:
    access_token_secret: github-token-reverse-aws-copilot-cd
    branch: main
    repository: https://github.com/simorgh1/aws-copilot-cd

# The deployment section defines the order the pipeline will deploy
# to your environments.
stages:
    - # The name of the environment to deploy to.
      name: test
      # Optional: flag for manual approval action before deployment.
      # requires_approval: true
      # Optional: use test commands to validate this stage of your build.
      test_commands:
        - npm install --prefix test
        - APP_URL=http://rever-test-1D7H4JMPNKE2Z-2143966135.eu-central-1.elb.amazonaws.com npm test --prefix test

    - # The name of the environment to deploy to.
      name: prod
      # Optional: flag for manual approval action before deployment.
      # requires_approval: true
      # Optional: use test commands to validate this stage of your build.
      # test_commands: [echo 'running tests', make test]

